### ISSUE TITLE
Add a abstract layer for streams library?

### ISSUE THREAD

**Issue by doofin** [raquo/Laminar#10]
I am using laminar now and find it very satisfying!(When using some very complex logic Outwatch gives nasty bug and It uses virtual dom so more difficult to debug),However I see you are developing new streams library airstream (https://github.com/raquo/laminar/pull/8),I worried that the new version with airstream take great effort for migration,so maybe we can add an abstract layer for streams library that allows using arbitrary stream library ?

**Comment by fdietze** [comment]
Great that you have this idea! I suggested exactly the same in outwatch: https://github.com/OutWatch/outwatch/issues/96

I'm imagining some typeclasses for reactive programming, like
```scala
  @typeclass
  trait Cancellable[C] {
    def cancel[F[_]:Effect](c:C):F[Unit]
  }
 
  object Source {
    def apply[M[_], C](implicit F: Source[M,C]) = F
  }
  trait Source[M[_], C] extends Applicative[M] {
 
    def subscribe[T, F[_]:Effect](s : M[T])(onNext: T => F[Unit])(implicit C: Cancellable[C]): F[C]
  }
 
  @typeclass
  trait Sink[M[_]] {
    def next[T,F[_]](s : M[T])(value: T): F[Unit]
  }
```

**Comment by raquo** [comment]
@doofin thanks! My concerns with having a streaming-agnostic library are outlined in the Outwatch thread that Felix linked. I definitely see potential upsides, but the downsides are too heavy for me. There is a big cost in having a streaming-agnostic solution, and I'm not sure if it's even feasible. It's not just about types, but how different streaming libraries behave under the hood.

I think the way to go is to implement Laminar with a lightweight streaming library like ~~Xstream~~ Airstream (#8), and optionally provide implicit conversions between Airstream streams and e.g. Monix or whatever people want.

Additionally, at this point my primary concern is getting the happy-path of Laminar working well. Extending it to other streaming libraries by any means is not a requirement for myself, and is thus not a priority right now. Once I integrate Airstream into Laminar it should be more obvious whether supporting multiple streaming libraries is possible / makes sense.

**Comment by raquo** [comment]
At this point I'm pretty sure this is not happening anytime soon for all of the above reasons, and also because Airstream has been working quite well, so I'm going to close this for now.
