### ISSUE TITLE
Safari cursor jumps to the end when an input value is set

### ISSUE THREAD

**Issue by pstutz** [raquo/Laminar#110]
It might make sense to also apply the controlled input Safari fix 695f2022bfedf4fe8d80f17835e1643de8e11827 when setting normal input values.

**Comment by raquo** [comment]
Hmmm I rarely add property-specific logic to Laminar, but this does seem like a good idea for the sake of ergonomics.

I'm currently very deep into the 0.15.0 changes, I might be able to address this there, but if not, then I'll deal with it soon after that.

On a side note, is there any specific reason why you're not using `controlled`? Simply no need, or does something about  not fit your use case?

**Comment by pstutz** [comment]
Thanks a lot for the response. `controlled` is exactly the workaround I ended up using after discovering that it contains the Safari fix. :)
