### ISSUE TITLE
Svg support?

### ISSUE THREAD

**Issue by doofin** [raquo/Laminar#12]
https://github.com/raquo/scala-dom-types/issues/20 what else needs to be done except for `scala-dom-types`?

**Comment by raquo** [comment]
Scala DOM Builder needs to be updated to handle

**Comment by raquo** [comment]
I've added a comment to that #20 issue, let's keep the discussion there until the scala dom builder changes materialize. Without those it's hard for me to judge what will be needed in Laminar.

Laminar changes will be easy as soon as we have SVG in DOM Builder with a tiny test in DOM Builder that 1) renders an SVG element with some children, and 2) verifies that it compiles and that correct SVG attributes or properties were set using [Scala DOM TestUtils](https://github.com/raquo/scala-dom-testutils)
