### ISSUE TITLE
Moving elements from one `children` list to another

### ISSUE THREAD

**Issue by raquo** [raquo/Laminar#120]
Suppose we have:

```scala
def isCool(el: ReactiveElement): Boolean = ???
val elements: Signal[List[ReactiveElement]] = ???
val coolElements = elements.map(_.filter(isCool))
val uncoolElements = elements.map(_.filterNot(isCool))

div(
  span(cls("cool"), children <-- coolElements),
  span(cls("uncool"), children <-- uncoolElements)
)
```

Basically, we're trying to break a single list into mutually exclusive (and exhaustive) lists of elements.

On the surface, we're not trying to render any element in more than one place at a time, so ideally this should work, but it doesn't – if you try this pattern, you will likely face the "Cannot read properties of null (reading 'nextSibling')" error.

In this snippet, elements are cached in the current value of the shared `elements` signal, and are moved from one `span` to another when their `isCool` status changes. The move consists of two steps – remove element from the old list, and add it to the new list, however we can't guarantee that these operations will actually happen in this order (because the order in which Airstream processes stream updates does not depend on the data of the events), and therein lies the problem, _I think_. 

Specifically, I think the problem arises when the signal into which the element was moved is processed by the corresponding `children <--` binder _first_, before the other signal from which that element was removed is processed by its corresponding `children <--`. In such a situation, the signal into which we moved the element sets the new parent of the element, removing it from its old location in the DOM. This works fine, but it introduces a discrepancy between real state of the DOM and what the other signal's `children <--` binder thinks the state of its managed DOM is. So when the latter binder finally gets to process the removal of the element from its signal, it chokes because it can't find the element to remove in its DOM (because it was already moved out of there by another binder).

^ This is a lot of words which is probably not clear to anyone but myself, but that's good enough for now, it's only a theory anyway.

--

This code pattern isn't exactly idiomatic Laminar style – our conventional wisdom is to avoid caching / reusing elements like this – but it might be necessary in situations where maximum performance is needed. So, ideally I would like to have this fixed.

I can try to make the `children <--` reconciliation logic more forgiving in situations where the element to be removed is not found in the list – the implementation would chalk it up to a timing mismatch such as this exact situation and assume that everything is ok. I'm not 100% sure that this is possible, will need to look into it later.

If it turns out to be not feasible, the documentation needs to be updated to reflect this limitation more clearly.

Original issue was [reported](https://gitter.im/Laminar_/Lobby?at=630fa2b705ad4a3701cc20d5) by @mattjacobus in gitter. See also [his own reproduction code](https://github.com/mattjacobus/move-groups/blob/main/modules/module2/src/main/scala/com/yurique/example/renders/Page1Render.scala) if my simple snippet above isn't enough to trigger the issue.

**Comment by raquo** [comment]
Happy to report that I was able to fix this. Now you'll be able to move elements between `children <-- observable` blocks, or even remove elements externally from a `children <-- observable` DOM block (assuming you also remove the same elements from the list emitted by `observable` of course).

While working on this, I've realized that right now, I can't give the same resilience to `child <-- observable` blocks, because they get rid of their sentinel comment node when the child is emitted (it replaces the invisible sentinel node, and the next child replaces the previous child, so if the previous child is not there – boom). I'm now working on keeping that sentinel node in the DOM similar to how `children` works, and also doing related improvements `child.text` while I'm at it.

**Comment by raquo** [comment]
Happy to report that I was able to fix this _for real this time_. Discovered more annoying issues with `onMountBind` (it lets you switch dynamically between different types of inserters), and finally fixed it all I think.

**Comment by yurique** [comment]
Amazing!

**Comment by mattjacobus** [comment]
Wow, great work!
