### ISSUE TITLE
RFC: Drop Scala 2.12 support

### ISSUE THREAD

**Issue by raquo** [raquo/Laminar#132]
If you need Laminar or Airstream to support Scala 2.12, or if you see any other reason to continue supporting 2.12, please let me know. Otherwise, I plan to drop support for Scala 2.12 in early 2024.

As of 2023-01-01, I'm aware of the following use cases for Scala 2.12:
* Sbt plugins
* Databricks
* Spark (although it does support 2.13 now)

I'm not familiar with Spark & Databricks usage patterns, but I wouldn't expect Laminar to be used in those codebases, since Laminar and Airstream don't run on the JVM, and those aren't the kinds of projects to need UIs or use Scala.js... I think?

Supporting Scala 2.12 is possible, but it costs me some time and annoyance, and I want to minimize both.

**Comment by Lasering** [comment]
This won't be a popular opinion but you should drop Scala 2.12 in Laminar 15. Anyone wanting to use Laminar with Scala 2.12 will stay at Laminar 14. If they wish to migrate they can first migrate to Scala 2.13 (and even Scala 3) using Laminar 14 and then migrate to Laminar 15.

**Comment by raquo** [comment]
Alrighty, in the last year nobody has spoken up in favor of keeping 2.12 support, so the upcoming Laminar 17.0.0 will drop it.
