### ISSUE TITLE
[Question] - jQuery bind and oninput event

### ISSUE THREAD

**Issue by mobilemindtec** [raquo/Laminar#135]
Hi,

How can I use a jquery plugin on a laminar input? I have created a facede component for number formatting and i'am using a datepicker component. However, when I call jQuery in the input, the laminar onInput stops working.

The JS plugin is this: https://plentz.github.io/jquery-maskmoney/

Exemple:

```
$("#minSale").maskMoney(MaskMoneyOpts())

  input(
    idAttr("minSale"),
    name("minSale"),
    controlled(
      value <-- stateVar.signal.map(_.minSale),
      onInput.mapToValue --> stateVar.updater((state, minSaleStr) => {
          println(s"copy minSale {$minSale}")
          state.copy(minSaleStr = minSaleStr)        
      })
    )
  )
```

Thanks for the help!

**Comment by raquo** [comment]
Hi, the `oninput` event not working seems to be a known issue with this maskmoney library: https://github.com/plentz/jquery-maskmoney/issues/122

Maybe try looking for a different library to do this. I'm still not sure if it would work but this one probably won't.

**Comment by mobilemindtec** [comment]
Hello,

You're right, this js plugin really works that way. I ended up using onblur.
Thanks.
