### ISSUE TITLE
tabIndex for SVG element

### ISSUE THREAD

**Issue by olynch** [raquo/Laminar#142]
According to https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/tabindex, it makes sense to set tabindex for SVG elements, but no `tabIndex` property for SVGElement in Laminar exists, only `tabIndex` as an `HtmlProp`.

As a workaround, I've been using `svgAttr("tabindex", StringAsIsCodec, None)`, which works perfectly fine, I just thought I'd file an issue for completeness's sake.

**Comment by raquo** [comment]
Good catch, I'll add it to SDT for the next release.

**Comment by olynch** [comment]
Thanks @raquo!

**Comment by raquo** [comment]
Fixed in 16.0.0 which will be released next week.
