### ISSUE TITLE
Observing inconsistent state

### ISSUE THREAD

**Issue by TomasStanek** [raquo/Laminar#174]
Hello,

in the following example, an inconsistent state (where a != b) is observed in both map and foreach.
On each button click, firstly an old value from `flatMappedSig` is observed together with a new value of `sig` and then they are observed consistently.

I'm using laminar 17.1.0

```scala
  def inconsistentState2() = {

    val initialVar = Var(1)

    val sig = initialVar.signal
    val flatMappedSig = sig.flatMapSwitch(_ => sig)

    Signal
      .combine(sig, flatMappedSig)
      .map { case (a, b) =>
        println("map:     " + (a == b, a, b))
        (a, b)
      }
      .foreach { case (a, b) =>
        println("foreach: " + (a == b, a, b))
      }(unsafeWindowOwner)

    div(
      button("button",  onClick --> Observer { _: Any => initialVar.set(Random.nextInt(100)) }),
    )
  }
```

Best regards,
Tomas Stanek

**Comment by yurique** [comment]
I added some debug logging here: https://scribble.ninja/u/yurique/cnlxsuogrouquabykzfdsanfzxx

With that `flatMapSwitch`, you're introducing a transaction boundary, so what happens is 
* first, `sig` gets a new value - `Signal.combine` updates, your `.map` and `.foreach` get executed - but `flatMappedSig` has not got updated yet
* next, the `flatMappedSig` evaluates a new value (in a new transaction) - `Signal.combine` updates again, and your `.map` and `.foreach` run again - now with both signals in-sync

(more details here - https://github.com/raquo/Airstream?tab=readme-ov-file#avoid-unnecessary-flatmap )

**Comment by TomasStanek** [comment]
I see. I wasn't aware that flatMap creates a new transaction. That explains it. Thank you.
