### ISSUE TITLE
XStream.js & diamond pattern

### ISSUE THREAD

**Issue by raquo** [raquo/Laminar#2]
@cornerman I looked into what we talked about regarding https://github.com/OutWatch/outwatch/issues/92

The [Xstream.combine](https://github.com/staltz/xstream#combine) operator behaves just like RXJS's `combineLatest` because in these streaming libraries a value emitted to a stream propagates all the way through the chain of its first listener before the library starts propagating it to the second listener. _I'm pretty sure..._

I haven't looked at how scala-rx is implemented, but I assume that it propagates new values shallowly, i.e. it first updates every immediate listener of a reactive variable, and only after that do those listeners update their own immediate listeners in the same manner. Sorry, using XStream terms here, I don't know what terms scala-rx uses.

I understand that this is somewhat of a problem for Outwatch because it uses `combineLatest` internally to generate fresh virtual nodes, but Laminar doesn't do any of those two things. Regarding end user code, I've rediscovered https://staltz.com/rx-glitches-arent-actually-a-problem.html and it got me convinced that – for now – I can live with this. The solution André proposes seems quite reasonable for end user code.

It probably won't suit Outwatch internals though because there you have no control over what streams you get from end users.

**Comment by cornerman** [comment]
Thanks for checking in xstream; both libraries work in similar fashion.

Sorry for the misunderstanding, but the `combineLatest` with multiple updates is not a problem in outwatch itself. But more of a problem we observed, when building an application on top of rx.js. This also lead us to further looking into state management vs. event streams, here we are working with scala.rx currently. We found that it is quite easy to introduce glitches with inconsistent data when just working with streams and its operators. We surely could construct it differently as also discussed in the link, but this might be error-prone and easy to overlook as I need to reason about the origin of each stream when I am combining. Or am I missing something?

**Comment by raquo** [comment]
Ah, I thought you were concerned about the briefly-incorrect state of the snabbdom node and/or the extra calls to snabbdom's patch method.

I'm still yet to fully process what Felix [wrote](https://github.com/OutWatch/outwatch/issues/96) about state vs events. I understand the difference, but didn't quite visualize the practical implications of having two systems yet.

**Comment by raquo** [comment]
Fixed in #8 with the magic of Airstream, so not relevant anymore. That PR will be the next version of Laminar soon.
