### ISSUE TITLE
Generate ScalaDoc to get an API reference

### ISSUE THREAD

**Issue by raquo** [raquo/Laminar#21]
This will reduce the need to surface every square inch of the API in the README too.

**Comment by pishen** [comment]
Have generated some scaladoc here using Travis & Github Pages

Laminar: https://pishen.github.io/Laminar/com/raquo/laminar/index.html
Airstream: https://pishen.github.io/Airstream/com/raquo/airstream/index.html
scala-dom-builder: https://pishen.github.io/scala-dom-builder/com/raquo/dombuilder/index.html
scala-dom-types: https://pishen.github.io/scala-dom-types/com/raquo/domtypes/index.html
* Cannot link from one scaladoc to another by clicking class name, maybe it requires [apiURL](https://www.scala-sbt.org/1.x/docs/Howto-Scaladoc.html#Define+the+location+of+API+documentation+for+a+library) to be set before publish?
* Some UI of the scaladoc are broken ([example](https://pishen.github.io/scala-dom-types/com/raquo/domtypes/generic/defs/reflectedAttrs/ReflectedAttrs.html#defaultSelected:RA[Boolean,Boolean]))

**Comment by raquo** [comment]
Well, new version is out, I'm gonna close this. I don't think I'll have time to do this anytime soon.
