### ISSUE TITLE
make laminar cross platform? android,ios,web...etc

### ISSUE THREAD

**Issue by doofin** [raquo/Laminar#29]
check this https://github.com/scalajs-react-interface/mobile.g8

**Comment by raquo** [comment]
This can't happen until / unless someone builds a business on Laminar and decides to fund this kind of development.

Even though some of Laminar dependencies are ready to accept alternative renderers, A LOT of work is needed to get this done. At the same time, native renders would provide only incremental benefits – all those platforms can display HTML+JS just fine, native is merely faster / smoother / richer, but it's not the only option on those platforms.

Personally I am willing to develop, maintain and support only small open source libraries, and the design of Scala DOM Types / Scala DOM Builder / Airstream / Laminar reflects that. A complex cross platform solution is not something I want to work on unless it's my job.

**Comment by raquo** [comment]
There are libraries like Cordova that do this, perhaps we'd benefit from a
Scala.js / sbt integration with such libraries, but this is not specific to
Laminar.

--
Nikita
