### ISSUE TITLE
idiomatic way with `addEventListener`

### ISSUE THREAD

**Issue by doofin** [raquo/Laminar#32]
Currently I implement touch event like this:
```scala
    s.svg(
      s.height := "800",
      s.width := "500",
      s.circle(
        inContext { e =>
          e.ref.addEventListener("touchmove", { e: TouchEvent =>
            println(e.changedTouches(0).clientX)
          })
          s.svg()
        },
        onMouseDown --> dragpipe,
        s.cx := "100",
        s.r := "30",
        s.fill := "red",
//        onDrag --> dragpipe,
        s.x := "1000",
        s.y <-- dragpipe.events.map(x => x.clientY.toString)
      ),
      s.text(child.text <-- dragpipe.events.map(x => "aa"))
    )

```

It works although looks bad.. It would be great if we can do sth like 
`onEvent("some event")-->eventbus`

**Comment by raquo** [comment]
So the issue here is that `onTouchMove` is not currently available in Scala DOM Types. Until it is, you can implement custom props / attributes the same way laminar implements other events:

    val onTouchMove = new ReactiveEventProp[dom.TouchEvent](key)
    div(onTouchMove --> eventBus)

I guess I should document this more explicitly

**Comment by doofin** [comment]
Thanks!
