### ISSUE TITLE
Estimate Laminar's runtime code size

### ISSUE THREAD

**Issue by raquo** [raquo/Laminar#40]
As suggested in https://github.com/scala-js/scala-js/issues/3556, the [source-map-explorer](https://www.npmjs.com/package/source-map-explorer) package can be used to estimate the effect of Laminar library code on the output bundle size. Due to dead code elimination optimization in Scala.js, actual numbers depend on user code, but an estimate based e.g. on [laminar-examples](https://github.com/raquo/laminar-examples) will provide end users with some reassurance that this library is indeed minimal.

**Comment by raquo** [comment]
So with Scala 2.12.8, Scala.js 0.6.28, fullOptJS, but **before** gzipping:
- Laminar: 29KB
- Airstream: 34KB
- Scala DOM Types & Scala DOM Builder: 6KB combined

Components implemented in Laminar are similarly lightweight. In my project I have ~70 UI-related files totaling ~2000 Scala LoC (w/o empty lines or comments) weigh ~50KB. Not all of them use Laminar, but the ones that do don't stand out in size. This is expected because Laminar usage is very straightforward: there is no code generation from macros. As your app grows, the components will grow your bundle size linearly, so it's good that this part is efficient in terms of size.

Overall I'm happy with those numbers. Laminar, all of its dependencies, and components written in it are a small portion of my total bundle size, which for example includes another ~500KB of various Scala and Scala.js library code (collections, scala.js runtime, etc.). But that part is not related to Laminar usage, just standard Scala.js tax for an app of this size.

Laminar:
![Laminar size](https://user-images.githubusercontent.com/532656/58362723-4e23dc80-7e4f-11e9-9490-a5f37b39acd8.png)

Airstream:
![Airstream size](https://user-images.githubusercontent.com/532656/58362724-4ebc7300-7e4f-11e9-82c8-e09a0d07772d.png)

---

Unrelatedly, one thing I really didn't like seeing in my app bundle was how much space upickle serializers take. Looks like it's 3+ KB per simple `macroRW` case class serializer, and that adds up really quickly, especially when you have sealed trait hierarchies of such case classes. But that's only my own problem, Laminar itself doesn't use or require upickle or any other third party libraries.

**Comment by yurique** [comment]
I'm using Circe for json atm, and it seems to be adding a lot as well (the derived codecs). I was thinking about switching to upickle, but it looks like it's not much better in this regard.

**Comment by objektwerks** [comment]
Interesting analysis and results. I'm using Circe as well. Umm....

**Comment by raquo** [comment]
Just noticed that a bit of `examples` code made its way into the bundle for some reason, even though it is not referenced anywhere in my project from which I got these stats. Maybe the `App` in there caused that, not sure. Anyway, moved it from `main` to `test` fixtures, so Laminar is 1.8KB slimmer now.
