### ISSUE TITLE
Release for scalajs 1.0.0

### ISSUE THREAD

**Issue by megri** [raquo/Laminar#51]
Since there are few (none?) external dependencies my hunch is that this should be pretty straight forward :)

**Comment by megri** [comment]
Should I create issues for associated raquo-projects?

**Comment by raquo** [comment]
Let me release v0.8.0 first, it's almost there. It will not depend on Scala
DOM Builder anymore so no need to update that one. After that, PRs welcome!
domtypes already has one, I have to look at it.

—
Best regards,
Nikita

**Comment by raquo** [comment]
Dun dun dun! The massive v0.8.0 update is out, and it works (only with) Scala.js 1.x. Didn't have time to update 0.7.2 for Scala.js 1.x, so you'll need to jump both Scala.js and Laminar versions at the same time. The Scala.js part should be trivial though.
