### ISSUE TITLE
amend() should return `this`

### ISSUE THREAD

**Issue by raquo** [raquo/Laminar#52]
Currently `div(...modifiers).amend(...more modifiers)` returns `Unit` because in general I don't like builder-style APIs that work on mutable instances (which ReactiveElement is), but I'm starting to think that this particular case might be warranted.

We already have warnings to not reuse ReactiveElement-s, and the whole concept of modifiers requires the basic knowledge that modifiers are applied to the element immediately upon creation.

Meanwhile, `el.amend()` returning `this` would be very useful when `el` is an element exposed by an independent component. Being able to easily amend-and-immediately-use such elements makes for some very good composition, for example:

```scala
div(
  "Enter your age: ",
  TextInputComponent(..params).amend(onInput --> ???)
)
```

That's a very easy way for `TextInputComponent` to not need to care which events the consumer wants. Thanks to @yurique for bringing this up in gitter, good point.

**Comment by yurique** [comment]
Thanks for considering this, @raquo!
