### ISSUE TITLE
Docs: Need examples of state management

### ISSUE THREAD

**Issue by raquo** [raquo/Laminar#6]
Var / StateVar

**Comment by doofin** [comment]
Using `scan` is not sufficient?

**Comment by raquo** [comment]
`scan` (`fold` in Airstream) is one of the available tools, yes, but even that one is not explicitly documented here. And while the documentation provides examples of EventBus usage, it's lacking specific examples for Var / StateVar. Which would be quite similar, but still worth mentioning explicitly.

**Comment by raquo** [comment]
Eh I think Airstream's docs on Var are enough for this. Closing.
