### ISSUE TITLE
L.render fails for element which is mounted in shadow root

### ISSUE THREAD

**Issue by pbuszka** [raquo/Laminar#84]
when rendering laminar into component which is within shadow root tree it incorrectly fails with "Unable to mount Laminar RootNode into an unmounted container.". It is the result of test RootNode.isNodeMounted which asumes dom.window is the ultimate root for all elements. The snippet below demostrates the problem
```
    console.log("domElement ChildNode.isDescendantOf", ChildNode.isDescendantOf(domElement, dom.document))
    val domElementDyn = domElement.asInstanceOf[js.Dynamic]
    domElementDyn.attachShadow(js.Dynamic.literal("mode" -> "open"))
    val div = org.scalajs.dom.document.createElement("div")
    domElementDyn.shadowRoot.appendChild(div)
    console.log("div in shadow root ChildNode.isDescendantOf window", ChildNode.isDescendantOf(div, dom.document))
    console.log("div in shadow root ChildNode.isDescendantOf shadow root", ChildNode.isDescendantOf(div, domElementDyn.shadowRoot.asInstanceOf[dom.Node]))
    L.render(div, widgetRenderer.widget(config))
```
it gives output:

```
domElement ChildNode.isDescendantOf true
div in shadow root ChildNode.isDescendantOf window false
div in shadow root ChildNode.isDescendantOf shadow root true
```
div mounted in shadow root is not recognized as mounted hence the exception

I thought about passing to ClassRoot an additional argument i.e domRoot with default value dom.window and use it for tests in isNodeMounted to handle the case

**Comment by raquo** [comment]
@pbuszka I fixed the implementation of isDescendantOf to be able to pass the shadow root boundary. Since we're going **up** the tree, I don't think there will be permissions issues with mode=closed.

I pushed the fix to the 0.12.0 branch. Could you please make sure that this solves your issue? I've tested with jsdom but it's best to confirm such fancy things in a real app.

**Comment by pbuszka** [comment]
It works like a charm :) both open and closed mode

BTW I made a PR to waypoint [https://github.com/raquo/Waypoint/pull/5](url) so it works with laminar 0.12-M1

**Comment by raquo** [comment]
Cool thanks! There are now two PRs that update Waypoint, I'll merge it all
together on the weekend
—
Best regards,
Nikita
