### ISSUE TITLE
Weird behavior when updating signal while element is unmounted

### ISSUE THREAD

**Issue by ngochai94** [raquo/Laminar#88]
Hi, I have the following code snippet:
```
    val dataValid = Var(true)
    val hideResult = Var(false)
    val resultNode = div(
      child <-- dataValid.signal.map { if (_) div("Valid") else div("Invalid") }
    )
    div(
      CheckboxL(isChecked = dataValid.signal, onChange = dataValid.writer)("Data valid"),
      CheckboxL(isChecked = hideResult.signal, onChange = hideResult.writer)("Hide result"),
      child <-- hideResult.signal.map { if (_) emptyNode else resultNode }
    )
```

which renders as below:
![image](https://user-images.githubusercontent.com/11330999/109298810-be526400-7866-11eb-9003-bc557a5581f8.png)

Now, if I click on "Hide result", then click on "Data valid" and finally click on "Hide result" to make the result visible again, I would expect the result text changed to "Invalid", but it doesn't:
![image](https://user-images.githubusercontent.com/11330999/109298988-f9549780-7866-11eb-8a7c-016aa386d9c1.png)

Clicking on "Data valid" again makes the result correct:
![image](https://user-images.githubusercontent.com/11330999/109299478-c232b600-7867-11eb-8a01-f592265b8a98.png)

Clicking on "Data valid" again changes the text to "Invalid" as expected:
![image](https://user-images.githubusercontent.com/11330999/109299540-d70f4980-7867-11eb-826a-5a83275f7e11.png)

I think this might relates to how Airstream passes values or it's just some anti-pattern in my example. In order to fix this, I need to change `child <-- hideResult.signal.map { if (_) emptyNode else resultNode }` to `div(hidden <-- hideResult.signal, resultNode)`

**Comment by yurique** [comment]
In plain laminar:
```scala
val dataValid  = Var(false)
val hideResult = Var(false)
val resultNode = div(
  "hide/show:",
  child <-- dataValid.signal
    .debugWithName("resultNode <-- dataValid.signal")
    .debugLogEvents()
    .map { if (_) div("Valid") else div("Invalid") }
)

div(
  div(
    label(input(tpe := "checkbox", checked <-- dataValid.signal, onChange.mapToChecked --> dataValid.writer), "Data valid"),
    label(input(tpe := "checkbox", checked <-- hideResult.signal, onChange.mapToChecked --> hideResult.writer), "Hide result"),
    div(
      "always shown:",
      child <-- dataValid.signal
        .debugWithName("div <-- dataValid.signal")
        .debugLogEvents()
        .map { if (_) div("Valid") else div("Invalid") }
    ),
    child.maybe <-- hideResult.signal.map { if (_) None else Some(resultNode) }
  )
)
```

The problem here is that when the `resultNode` is removed from the dom, it stops listening to `dataValid.signal` and kind of "freezes in time". When you render it back, it starts listening again, but it's in the exact same "state" as it was when it was being removed from dom.

One way of making it work is like you did – hiding the element with css rather than removing it from dom.

Another way here would be making `val resultNode = div(...)` a `def` (`def resultNode = div(...)`).

I think this PR is intended to fix situations like this: https://github.com/raquo/Airstream/pull/69

**Comment by raquo** [comment]
Thanks @yurique, this is 100% correct. I will definitely fix the underlying issue (https://github.com/raquo/Airstream/issues/43) at some point, it's relatively high on my list.

Let's keep this issue open for visibility.

**Comment by nghuuphuoc** [comment]
I have faced this issue today. The current workaround is to hide the element using CSS :(

**Comment by raquo** [comment]
Solved in newly released Laminar 15.
