### ISSUE TITLE
Scala 3 support is here

### ISSUE THREAD

**Issue by raquo** [raquo/Laminar#93]
The following versions are published for Scala 3.0.0-RC2:

* Laminar 0.13.0-M1
* Airstream 0.13.0-M1
* Waypoint 0.4.0-M2
* tulz-app/frountroute 0.13.0-M2
* tulz-app/laminext 0.13.0-M1 (without circe JSON module yet)

These Laminar / Airstream versions should have no breaking changes from 0.12.x except if you manually extended Airstream traits EventStream, Signal, or Observable (in which case you should now extend WritableEventStream, WritableSignal, or WritableObservable respectively), due to internal refactoring of Airstream observables in 0.13.0-M1 to satisfy stricter variance checks in Scala 3.

Please use this ticket to report any issues with Scala 3 support.

**Comment by raquo** [comment]
v0.13.0 is released now https://laminar.dev/blog/2021/05/04/laminar-v0.13.0

Waypoint 0.4.0 is not yet published for Scala 3.0.0-RC3, coming soon.

**Comment by raquo** [comment]
Waypoint 0.4.0 published for RC3 now.

**Comment by rparree** [comment]
I am trying to update a project to scala 3.0.0:

```
ThisBuild / scalaVersion := "3.0.0"

lazy val root = (crossProject(JSPlatform, JVMPlatform) in file("."))
  .settings(
    name := "Setup front-end",
    libraryDependencies ++= Seq(

      "com.lihaoyi" %%% "utest" % "0.7.10" % "test",
      "com.raquo" %%% "laminar" % "0.13.0",
       …
    )

  )
```

i get the following error (i must be overseeing something ?)

```
sbt.librarymanagement.ResolveException: Error downloading com.raquo:laminar_3:0.13.0
```

I'm using `sbt-scalajs` 1.5.1

I tried also pulling this repo and use `publishLocal`, to no avail.

tx.,

**Comment by raquo** [comment]
Hi, you're trying to add Laminar to both JS and JVM subprojects. Laminar is
not available on the JVM. Make sure to add it only to the JS subproject.

--Nikita
